/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidationInboxRouteImport } from './routes/_authenticated/validation-inbox'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin/skills'
import { Route as AuthenticatedAdminProfilesIndexRouteImport } from './routes/_authenticated/admin/profiles.index'
import { Route as AuthenticatedAdminProfilesProfileIdIndexRouteImport } from './routes/_authenticated/admin/profiles.$profileId.index'
import { Route as AuthenticatedAdminProfilesProfileIdSeniorityRouteImport } from './routes/_authenticated/admin/profiles.$profileId.seniority'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidationInboxRoute =
  AuthenticatedValidationInboxRouteImport.update({
    id: '/validation-inbox',
    path: '/validation-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/skills',
    path: '/skills',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfilesIndexRoute =
  AuthenticatedAdminProfilesIndexRouteImport.update({
    id: '/profiles/',
    path: '/profiles/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfilesProfileIdIndexRoute =
  AuthenticatedAdminProfilesProfileIdIndexRouteImport.update({
    id: '/profiles/$profileId/',
    path: '/profiles/$profileId/',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminProfilesProfileIdSeniorityRoute =
  AuthenticatedAdminProfilesProfileIdSeniorityRouteImport.update({
    id: '/profiles/$profileId/seniority',
    path: '/profiles/$profileId/seniority',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/profiles': typeof AuthenticatedAdminProfilesIndexRoute
  '/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
  '/admin/profiles/$profileId': typeof AuthenticatedAdminProfilesProfileIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/login': typeof authLoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/profiles': typeof AuthenticatedAdminProfilesIndexRoute
  '/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
  '/admin/profiles/$profileId': typeof AuthenticatedAdminProfilesProfileIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/profiles/': typeof AuthenticatedAdminProfilesIndexRoute
  '/_authenticated/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
  '/_authenticated/admin/profiles/$profileId/': typeof AuthenticatedAdminProfilesProfileIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/validation-inbox'
    | '/admin/skills'
    | '/admin/profiles'
    | '/admin/profiles/$profileId/seniority'
    | '/admin/profiles/$profileId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/admin'
    | '/login'
    | '/profile'
    | '/validation-inbox'
    | '/admin/skills'
    | '/admin/profiles'
    | '/admin/profiles/$profileId/seniority'
    | '/admin/profiles/$profileId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/_authenticated/admin'
    | '/(auth)/login'
    | '/_authenticated/profile'
    | '/_authenticated/validation-inbox'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/profiles/'
    | '/_authenticated/admin/profiles/$profileId/seniority'
    | '/_authenticated/admin/profiles/$profileId/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validation-inbox': {
      id: '/_authenticated/validation-inbox'
      path: '/validation-inbox'
      fullPath: '/validation-inbox'
      preLoaderRoute: typeof AuthenticatedValidationInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profiles/': {
      id: '/_authenticated/admin/profiles/'
      path: '/profiles'
      fullPath: '/admin/profiles'
      preLoaderRoute: typeof AuthenticatedAdminProfilesIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profiles/$profileId/': {
      id: '/_authenticated/admin/profiles/$profileId/'
      path: '/profiles/$profileId'
      fullPath: '/admin/profiles/$profileId'
      preLoaderRoute: typeof AuthenticatedAdminProfilesProfileIdIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/admin/profiles/$profileId/seniority': {
      id: '/_authenticated/admin/profiles/$profileId/seniority'
      path: '/profiles/$profileId/seniority'
      fullPath: '/admin/profiles/$profileId/seniority'
      preLoaderRoute: typeof AuthenticatedAdminProfilesProfileIdSeniorityRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminProfilesIndexRoute: typeof AuthenticatedAdminProfilesIndexRoute
  AuthenticatedAdminProfilesProfileIdSeniorityRoute: typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
  AuthenticatedAdminProfilesProfileIdIndexRoute: typeof AuthenticatedAdminProfilesProfileIdIndexRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
    AuthenticatedAdminProfilesIndexRoute: AuthenticatedAdminProfilesIndexRoute,
    AuthenticatedAdminProfilesProfileIdSeniorityRoute:
      AuthenticatedAdminProfilesProfileIdSeniorityRoute,
    AuthenticatedAdminProfilesProfileIdIndexRoute:
      AuthenticatedAdminProfilesProfileIdIndexRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedValidationInboxRoute: typeof AuthenticatedValidationInboxRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedValidationInboxRoute: AuthenticatedValidationInboxRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
