/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedValidationInboxRouteImport } from './routes/_authenticated/validation-inbox'
import { Route as AuthenticatedProfileRouteImport } from './routes/_authenticated/profile'
import { Route as authLoginRouteImport } from './routes/(auth)/login'
import { Route as AuthenticatedAdminSkillsRouteImport } from './routes/_authenticated/admin/skills'
import { Route as AuthenticatedAdminProfilesProfileIdSeniorityRouteImport } from './routes/_authenticated/admin/profiles.$profileId.seniority'

const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedValidationInboxRoute =
  AuthenticatedValidationInboxRouteImport.update({
    id: '/validation-inbox',
    path: '/validation-inbox',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedProfileRoute = AuthenticatedProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const authLoginRoute = authLoginRouteImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminSkillsRoute =
  AuthenticatedAdminSkillsRouteImport.update({
    id: '/admin/skills',
    path: '/admin/skills',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminProfilesProfileIdSeniorityRoute =
  AuthenticatedAdminProfilesProfileIdSeniorityRouteImport.update({
    id: '/admin/profiles/$profileId/seniority',
    path: '/admin/profiles/$profileId/seniority',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof authLoginRoute
  '/profile': typeof AuthenticatedProfileRoute
  '/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/_authenticated/profile': typeof AuthenticatedProfileRoute
  '/_authenticated/validation-inbox': typeof AuthenticatedValidationInboxRoute
  '/_authenticated/admin/skills': typeof AuthenticatedAdminSkillsRoute
  '/_authenticated/admin/profiles/$profileId/seniority': typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/profile'
    | '/validation-inbox'
    | '/admin/skills'
    | '/admin/profiles/$profileId/seniority'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/profile'
    | '/validation-inbox'
    | '/admin/skills'
    | '/admin/profiles/$profileId/seniority'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/(auth)/login'
    | '/_authenticated/profile'
    | '/_authenticated/validation-inbox'
    | '/_authenticated/admin/skills'
    | '/_authenticated/admin/profiles/$profileId/seniority'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  authLoginRoute: typeof authLoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/validation-inbox': {
      id: '/_authenticated/validation-inbox'
      path: '/validation-inbox'
      fullPath: '/validation-inbox'
      preLoaderRoute: typeof AuthenticatedValidationInboxRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/profile': {
      id: '/_authenticated/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AuthenticatedProfileRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/skills': {
      id: '/_authenticated/admin/skills'
      path: '/admin/skills'
      fullPath: '/admin/skills'
      preLoaderRoute: typeof AuthenticatedAdminSkillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin/profiles/$profileId/seniority': {
      id: '/_authenticated/admin/profiles/$profileId/seniority'
      path: '/admin/profiles/$profileId/seniority'
      fullPath: '/admin/profiles/$profileId/seniority'
      preLoaderRoute: typeof AuthenticatedAdminProfilesProfileIdSeniorityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedProfileRoute: typeof AuthenticatedProfileRoute
  AuthenticatedValidationInboxRoute: typeof AuthenticatedValidationInboxRoute
  AuthenticatedAdminSkillsRoute: typeof AuthenticatedAdminSkillsRoute
  AuthenticatedAdminProfilesProfileIdSeniorityRoute: typeof AuthenticatedAdminProfilesProfileIdSeniorityRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedProfileRoute: AuthenticatedProfileRoute,
  AuthenticatedValidationInboxRoute: AuthenticatedValidationInboxRoute,
  AuthenticatedAdminSkillsRoute: AuthenticatedAdminSkillsRoute,
  AuthenticatedAdminProfilesProfileIdSeniorityRoute:
    AuthenticatedAdminProfilesProfileIdSeniorityRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  authLoginRoute: authLoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
