import {
  SiReact,
  SiNextdotjs,
  SiVuedotjs,
  SiAngular,
  SiSvelte,
  SiNuxtdotjs,
  SiAndroid,
  SiTailwindcss,
  SiHtml5,
  SiCss3,
  SiSass,
  SiStyledcomponents,
  SiBootstrap,
  SiTypescript,
  SiJavascript,
  SiPython,
  SiSharp,
  SiCplusplus,
  SiC,
  SiGo,
  SiRust,
  SiPhp,
  SiRuby,
  SiSwift,
  SiKotlin,
  SiDart,
  SiScala,
  SiElixir,
  SiErlang,
  SiJquery,
  SiNodedotjs,
  SiExpress,
  SiNestjs,
  SiDjango,
  SiFlask,
  SiFastapi,
  SiSpringboot,
  SiDotnet,
  SiLaravel,
  SiRubyonrails,
  SiPostgresql,
  SiMysql,
  SiMongodb,
  SiRedis,
  SiSqlite,
  SiAmazondynamodb,
  SiNeo4J,
  SiInfluxdb,
  SiElasticsearch,
  SiAmazonwebservices,
  SiGooglecloud,
  SiVercel,
  SiNetlify,
  SiHeroku,
  SiDigitalocean,
  SiRailway,
  SiRender,
  SiSupabase,
  SiFirebase,
  SiPlanetscale,
  SiCloudflare,
  SiDocker,
  SiKubernetes,
  SiTerraform,
  SiAnsible,
  SiJenkins,
  SiGithubactions,
  SiGitlab,
  SiCircleci,
  SiNginx,
  SiApache,
  SiGit,
  SiGithub,
  SiBitbucket,
  SiFigma,
  SiAdobexd,
  SiSketch,
  SiAdobephotoshop,
  SiAdobeillustrator,
  SiGraphql,
  SiApollographql,
  SiRelay,
  SiTrpc,
  SiJest,
  SiCypress,
  SiElectron,
  SiTestinglibrary,
  SiVitest,
  SiSelenium,
  SiFlutter,
  SiIonic,
  SiExpo,
  SiWebpack,
  SiVite,
  SiRollupdotjs,
  SiTurborepo,
  SiLerna,
  SiWebassembly,
  SiSocketdotio,
  SiUipath,
  SiStripe,
  SiStorybook,
  SiShopify,
  SiBlazor,
  SiUnity,
  SiRoku,
  SiTensorflow,
  SiWebflow,
  SiFramer,
  SiK6,
  SiSonarqube,
  SiSnyk,
  SiJetpackcompose,
  SiGradle,
  SiJunit5,
  SiUikit,
  SiXml,
  SiIos,
} from 'react-icons/si'

// Fallback icons from Lucide for missing brand icons
import {
  AppWindow,
  Drama,
  Network,
  Coffee,
  Database,
  Cloud,
  Package,
  Zap,
} from 'lucide-react'

export const skillIcons = {
  React: SiReact,
  'React JS': SiReact,
  'Next.js': SiNextdotjs,
  NextJs: SiNextdotjs,
  'Vue.js': SiVuedotjs,
  Angular: SiAngular,
  Svelte: SiSvelte,
  'Nuxt.js': SiNuxtdotjs,

  // Styling & Design
  'Tailwind CSS': SiTailwindcss,
  HTML: SiHtml5,
  CSS: SiCss3,
  'Sass/SCSS': SiSass,
  'Styled Components': SiStyledcomponents,
  Bootstrap: SiBootstrap,

  // Programming Languages
  TypeScript: SiTypescript,
  JavaScript: SiJavascript,
  Python: SiPython,
  Java: Coffee,
  'C#': SiSharp,
  'C++': SiCplusplus,
  C: SiC,
  Go: SiGo,
  Rust: SiRust,
  PHP: SiPhp,
  Ruby: SiRuby,
  'Objective-C': SiSwift,
  Swift: SiSwift,
  Kotlin: SiKotlin,
  Dart: SiDart,
  Scala: SiScala,
  Elixir: SiElixir,
  Erlang: SiErlang,

  // Backend & Runtime
  'Node.js': SiNodedotjs,
  'Node JS': SiNodedotjs,
  'Express.js': SiExpress,
  'Nest.js': SiNestjs,
  Django: SiDjango,
  Flask: SiFlask,
  FastAPI: SiFastapi,
  'Spring Boot': SiSpringboot,
  '.NET': SiDotnet,
  Laravel: SiLaravel,
  'Ruby on Rails': SiRubyonrails,
  Gin: SiGo,
  Fiber: SiGo,

  // Databases
  PostgreSQL: SiPostgresql,
  MySQL: SiMysql,
  MongoDB: SiMongodb,
  Redis: SiRedis,
  SQLite: SiSqlite,
  Cassandra: Database,
  DynamoDB: SiAmazondynamodb,
  Neo4j: SiNeo4J,
  InfluxDB: SiInfluxdb,
  Elasticsearch: SiElasticsearch,

  // Cloud Providers
  AWS: SiAmazonwebservices,
  'Google Cloud': SiGooglecloud,
  'Microsoft Azure': Cloud,
  Vercel: SiVercel,
  Netlify: SiNetlify,
  Heroku: SiHeroku,
  DigitalOcean: SiDigitalocean,
  Linode: Cloud,
  Railway: SiRailway,
  Render: SiRender,
  Supabase: SiSupabase,
  Firebase: SiFirebase,
  PlanetScale: SiPlanetscale,
  Cloudflare: SiCloudflare,

  // DevOps & Tools
  Docker: SiDocker,
  Kubernetes: SiKubernetes,
  Terraform: SiTerraform,
  Ansible: SiAnsible,
  Jenkins: SiJenkins,
  'GitHub Actions': SiGithubactions,
  'GitLab CI': SiGitlab,
  CircleCI: SiCircleci,
  Nginx: SiNginx,
  Apache: SiApache,

  // Version Control
  Git: SiGit,
  GitHub: SiGithub,
  GitLab: SiGitlab,
  Bitbucket: SiBitbucket,

  // Design Tools
  Design: SiFigma,
  Figma: SiFigma,
  'Adobe XD': SiAdobexd,
  Sketch: SiSketch,
  Photoshop: SiAdobephotoshop,
  Illustrator: SiAdobeillustrator,

  // API & GraphQL
  GraphQL: SiGraphql,
  'REST API': Network,
  Apollo: SiApollographql,
  Relay: SiRelay,
  tRPC: SiTrpc,
  JQuery: SiJquery,

  // Testing
  Jest: SiJest,
  Cypress: SiCypress,
  Playwright: Drama,
  'Testing Library': SiTestinglibrary,
  QA: SiTestinglibrary,
  'Manual QA': SiTestinglibrary,
  Vitest: SiVitest,
  Selenium: SiSelenium,
  JUnit: SiJunit5,

  // Performance Testing
  JMeter: Zap,
  K6: SiK6,

  // Security Testing
  SonarQube: SiSonarqube,
  Snyk: SiSnyk,

  // Mobile Development
  'React Native': SiReact,
  Android: SiAndroid,
  iOS: SiIos,
  Flutter: SiFlutter,
  Ionic: SiIonic,
  Expo: SiExpo,

  // iOS Development
  SwiftUI: SiSwift,
  UIKit: SiUikit,

  // Android Development
  'Jetpack Compose': SiJetpackcompose,
  'XML Layouts': SiXml,
  Gradle: SiGradle,

  // Desktop & Hybrid
  Electron: SiElectron,

  // Build Tools & Bundlers
  Webpack: SiWebpack,
  Vite: SiVite,
  Rollup: SiRollupdotjs,
  Parcel: Package,
  Turborepo: SiTurborepo,
  Lerna: SiLerna,

  // E-commerce & No-Code
  Webflow: SiWebflow,
  Framer: SiFramer,

  // Other Technologies
  'Power Apps': AppWindow,
  UiPath: SiUipath,
  'Machine Learning': SiTensorflow,
  Shopify: SiShopify,
  WebAssembly: SiWebassembly,
  'Socket.io': SiSocketdotio,
  Stripe: SiStripe,
  Storybook: SiStorybook,
  Blazor: SiBlazor,
  Unity: SiUnity,
  Roku: SiRoku,
  'Workfront Fusion': Package,
}
